import { RocketSkin, Badge, PlayerStats } from '../types/game';

export const INITIAL_SKINS: RocketSkin[] = [
  {
    id: 'blue',
    name: 'Cosmo Blue',
    themeColor: '#00d2ff',
    accentColor: '#a5e7ff',
    badge: 'DEFAULT',
    speedBonus: 1.0,
    magnetBonus: 1.0,
    shieldBonus: 1.0,
    unlocked: true,
    cost: 0,
    description: 'Chubby agile electric-cyan flyer with friendly bubble visor and responsive side thrusters.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRecXtZJs16UWkY7J9LegjMIN64abgRwgVMM_YTaRSFq8XQqdTN6ERU2Wx7PVysdBXBzW7pjJxukrSauRGZL5Zc1ExXEt2oVaLxUmJ7J5dkOOoRRctGCug8K9P70liwVQ-sDAs3o5s9tb6aRP8Aqi_hrNtVi5IGdwJ0pyJF5-ZthbCspR4q0AmhDKsm1EdT4UHXvOAAkETgiIGyyPhlL_KEEphU7EYlZdxIH8difyNTaFMII0HF6nMPA',
  },
  {
    id: 'red',
    name: 'Solar Red',
    themeColor: '#ff5261',
    accentColor: '#ffdad9',
    badge: 'HIGH SPEED',
    speedBonus: 1.25,
    magnetBonus: 0.9,
    shieldBonus: 1.0,
    unlocked: true,
    cost: 500,
    description: 'Energetic crimson speedster featuring twin booster pods and rapid lane cutaways.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRecXtZJs16UWkY7J9LegjMIN64abgRwgVMM_YTaRSFq8XQqdTN6ERU2Wx7PVysdBXBzW7pjJxukrSauRGZL5Zc1ExXEt2oVaLxUmJ7J5dkOOoRRctGCug8K9P70liwVQ-sDAs3o5s9tb6aRP8Aqi_hrNtVi5IGdwJ0pyJF5-ZthbCspR4q0AmhDKsm1EdT4UHXvOAAkETgiIGyyPhlL_KEEphU7EYlZdxIH8difyNTaFMII0HF6nMPA',
  },
  {
    id: 'yellow',
    name: 'Sparkle Yellow',
    themeColor: '#fecf00',
    accentColor: '#fff0c9',
    badge: 'STAR MAGNET',
    speedBonus: 0.95,
    magnetBonus: 1.45,
    shieldBonus: 1.1,
    unlocked: true,
    cost: 800,
    description: 'Golden star seeker outfitted with wide-band stardust gravity collectors.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRecXtZJs16UWkY7J9LegjMIN64abgRwgVMM_YTaRSFq8XQqdTN6ERU2Wx7PVysdBXBzW7pjJxukrSauRGZL5Zc1ExXEt2oVaLxUmJ7J5dkOOoRRctGCug8K9P70liwVQ-sDAs3o5s9tb6aRP8Aqi_hrNtVi5IGdwJ0pyJF5-ZthbCspR4q0AmhDKsm1EdT4UHXvOAAkETgiIGyyPhlL_KEEphU7EYlZdxIH8difyNTaFMII0HF6nMPA',
  },
  {
    id: 'vortex',
    name: 'Vortex Mk-II',
    themeColor: '#00f2fe',
    accentColor: '#6ff6ff',
    badge: 'HYPERSONIC',
    speedBonus: 1.4,
    magnetBonus: 1.2,
    shieldBonus: 1.3,
    unlocked: true,
    cost: 1500,
    description: 'Hypersonic orbital interceptor with variable geometry wings and quantum lock canopy.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRecXtZJs16UWkY7J9LegjMIN64abgRwgVMM_YTaRSFq8XQqdTN6ERU2Wx7PVysdBXBzW7pjJxukrSauRGZL5Zc1ExXEt2oVaLxUmJ7J5dkOOoRRctGCug8K9P70liwVQ-sDAs3o5s9tb6aRP8Aqi_hrNtVi5IGdwJ0pyJF5-ZthbCspR4q0AmhDKsm1EdT4UHXvOAAkETgiIGyyPhlL_KEEphU7EYlZdxIH8difyNTaFMII0HF6nMPA',
  }
];

export const INITIAL_PLAYER_STATS: PlayerStats = {
  coins: 2450,
  bestScore: 12450,
  highRecord: 18920,
  totalFlights: 14,
  totalDistanceKm: 68.4,
  totalStarsGrabbed: 842,
  level: 28,
  xp: 3400,
  nextLevelXp: 4000,
  activeSkin: 'blue',
  soundEnabled: true,
  upgrades: {
    thrusterLevel: 2,
    shieldLevel: 1,
    magnetLevel: 2,
    boostLevel: 3,
  }
};

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'first-flight',
    title: 'First Blastoff',
    description: 'Complete your first successful mission flight in deep space',
    icon: 'rocket_launch',
    unlocked: true,
    progress: 1,
    maxProgress: 1,
    rewardCoins: 100,
  },
  {
    id: 'star-collector',
    title: 'Star Hoarder',
    description: 'Collect 500 gold cosmic star coins during your career',
    icon: 'stars',
    unlocked: true,
    progress: 842,
    maxProgress: 500,
    rewardCoins: 250,
  },
  {
    id: 'speed-demon',
    title: 'Super Fast!',
    description: 'Sustain maximum boost velocity for over 15 seconds',
    icon: 'bolt',
    unlocked: true,
    progress: 18,
    maxProgress: 15,
    rewardCoins: 300,
  },
  {
    id: 'asteroid-evader',
    title: 'Master Dodger',
    description: 'Dodge 150 cosmic asteroids without suffering shield collapse',
    icon: 'shield',
    unlocked: false,
    progress: 112,
    maxProgress: 150,
    rewardCoins: 400,
  },
  {
    id: 'distance-walker',
    title: 'Galactic Voyager',
    description: 'Accumulate over 100 km total distance traveled across sectors',
    icon: 'explore',
    unlocked: false,
    progress: 68.4,
    maxProgress: 100,
    rewardCoins: 500,
  },
  {
    id: 'champion',
    title: 'Sector 7 Ace',
    description: 'Achieve a single flight score exceeding 20,000 points',
    icon: 'military_tech',
    unlocked: false,
    progress: 12450,
    maxProgress: 20000,
    rewardCoins: 1000,
  },
];

export const LEADERBOARD_ENTRIES = [
  { rank: 1, name: 'HYPER_NOVA', score: 142880, badge: '🏆 GOLD', level: 45 },
  { rank: 2, name: 'ZERO_KELVIN', score: 129410, badge: '🥈 SILVER', level: 41 },
  { rank: 3, name: 'ASTRO_BLAZE', score: 115200, badge: '🥉 BRONZE', level: 38 },
  { rank: 4, name: 'STELLAR_FOX', score: 108450, badge: 'TOP 5', level: 35 },
  { rank: 5, name: 'NEBULA_KID', score: 104200, badge: 'TOP 5', level: 33 },
  { rank: 14, name: 'YOU (VORTEX-9)', score: 98420, isUser: true, badge: 'COMMANDER', level: 28 },
  { rank: 15, name: 'CYBER_DRIFT', score: 97110, badge: 'VETERAN', level: 27 },
  { rank: 16, name: 'PULSE_RIDER', score: 93400, badge: 'PILOT', level: 25 },
];
